version: '2'
services:
  my-mean-app:
    restart: always
    build: .
    ports:
     - "3000:3000"
    environment:
     - NODE_ENV=development
     - MONGODB_HOST=node_my-mean-db_1
     - MONGODB_USERNAME=myusername
     - MONGODB_PASSWORD=myusernametrickylongpassword
     - MONGODB_DATABASE=mydb
    depends_on:
      - my-mean-db
  my-mean-db:
    image: bitnami/mongodb:3.4.3-r0
    restart: always
    ports:
     - "27017:27017"
    environment:
     - MONGODB_USERNAME=myusername
     - MONGODB_PASSWORD=myusernametrickylongpassword
     - MONGODB_DATABASE=mydb
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb

